name: ai_chat_bot
description: An intelligent AI chat bot application powered by advanced language models
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2
  http_parser: ^4.0.0
  intl: ^0.18.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  file_picker: ^10.1.4
  data_table_2: ^2.5.10
  # Temporarily disabled due to build issues
  # google_mobile_ads: ^3.1.0
  in_app_purchase: ^3.1.11
  dio: ^5.4.0
  google_sign_in: ^6.2.1  
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  mime: ^1.0.4
  path: ^1.8.3  
  flutter_markdown: ^0.7.7+1  
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  # Thêm Firebase Crashlytics để theo dõi sự cố
  firebase_crashlytics: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  mocktail: ^1.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter_18pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_18pt-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geist/Geist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geist/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist/Geist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Geist/Geist-Black.ttf
          weight: 900
