// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Windows uses the web config with Desktop OAuth flow
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkVxfV1SMF7iORASUZGVPa2HoIIa5KEk',
    appId: '1:784300763720:web:d8b6a3ab0a3d88bc318583',
    messagingSenderId: '784300763720',
    projectId: 'ai-chat-buddy-1',
    authDomain: 'ai-chat-buddy-1.firebaseapp.com',
    storageBucket: 'ai-chat-buddy-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tvt5XUX9OJtABKNmoUQMx3FS8MTihtw',
    appId: '1:784300763720:android:85e47ef47f5bca2e318583',
    messagingSenderId: '784300763720',
    projectId: 'ai-chat-buddy-1',
    storageBucket: 'ai-chat-buddy-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTubsUAe46asLmQR6OGQR_QpMpfbiE0I',
    appId: '1:784300763720:ios:5c354a0e9f65d6ec318583',
    messagingSenderId: '784300763720',
    projectId: 'ai-chat-buddy-1',
    storageBucket: 'ai-chat-buddy-1.appspot.com',
    iosBundleId: 'com.example.aiChatBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRTubsUAe46asLmQR6OGQR_QpMpfbiE0I',
    appId: '1:784300763720:ios:5c354a0e9f65d6ec318583',
    messagingSenderId: '784300763720',
    projectId: 'ai-chat-buddy-1',
    storageBucket: 'ai-chat-buddy-1.appspot.com',
    iosBundleId: 'com.example.aiChatBuddy',
  );
}