// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBssJsq45UfWALFmi5R_HYWv7-mnVPy2jw',
    appId: '1:784300763720:web:1f46d71b30037faafe067d',
    messagingSenderId: '784300763720',
    projectId: 'vinh-aff13',
    authDomain: 'vinh-aff13.firebaseapp.com',
    storageBucket: 'vinh-aff13.firebasestorage.app',
    measurementId: 'G-4ZT6NC3STN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaKsurA5ZDawvgcuOGO8qc7TOJIAOegM',
    appId: '1:784300763720:android:db9bbff664f9acd5fe067d',
    messagingSenderId: '784300763720',
    projectId: 'vinh-aff13',
    storageBucket: 'vinh-aff13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQ5WhajaiVj5GuacnSP5jdeJPk6uFmiw',
    appId: '1:784300763720:ios:75937b646858bd78fe067d',
    messagingSenderId: '784300763720',
    projectId: 'vinh-aff13',
    storageBucket: 'vinh-aff13.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQ5WhajaiVj5GuacnSP5jdeJPk6uFmiw',
    appId: '1:784300763720:ios:75937b646858bd78fe067d',
    messagingSenderId: '784300763720',
    projectId: 'vinh-aff13',
    storageBucket: 'vinh-aff13.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBssJsq45UfWALFmi5R_HYWv7-mnVPy2jw',
    appId: '1:784300763720:web:ef5e09848323fb71fe067d',
    messagingSenderId: '784300763720',
    projectId: 'vinh-aff13',
    authDomain: 'vinh-aff13.firebaseapp.com',
    storageBucket: 'vinh-aff13.firebasestorage.app',
    measurementId: 'G-42WRR6CNNF',
  );
}
